apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-doc
spec:
  displayName: Doc
  author:
    name: Halo OSS Organization
    website: https://halo.run
  description: 
  logo: https://halo.run/logo
  website: https://github.com/ruibaby/theme-doc
  repo: https://github.com/ruibaby/theme-doc.git
  settingName: "theme-doc-setting"
  configMapName: "theme-doc-configMap"
  version: 1.0.0
  require: 2.0.0
